#!/usr/bin/env python2


def main():
    stack = {}
    functions = {}
    calls = []

    for line in open('lc.perf'):
        parts = line.strip().split()
        name = parts[0]
        if name == 'funcname':
            functions[parts[1]] = parts[2]
        elif name == 'call':
            stack.setdefault(parts[1], []).append(parts[2])
        elif name == 'endcall':
            call = stack[parts[1]].pop()
            calls.append([parts[1], float(call), float(parts[2])])

    named_calls = []
    times = {}
    for address, start, end in calls:
        if address not in functions:
            continue
        name = functions[address]
        named_calls.append([name, start, end])
        times.setdefault(name, []).append(end - start)

    total_times = sorted([
        (sum(interval), name)
        for name, interval in times.items()
    ], reverse=True)

    for time, name in total_times:
        print '%12.6f' % time, name

main()
